// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myhccubuqtpedzfkzyhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15aGNjdWJ1cXRwZWR6Zmt6eWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTQxNTYsImV4cCI6MjA2MTc5MDE1Nn0.YvbizjuA6jc1tqFOSIrP-caOHJVcnH2fpzlx3GXthjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);